export const config = {
  halcyon: {
    videotitle: "",
    videodescription: "",
    playerBrandingImageUrl:
      "https://sato-image-content.b-cdn.net/48d677f8-734a-496e-a2ec-ad6ef88411cc/50c87637-98f8-4378-b5b1-0f7a595a1b21/Sato.svg",
    playerThumbnailImageUrl: "",
    playersettings: {
      autoplay: false,
      muted: false,
      loop: false,
      use_as_BG_video: false,
    },
    playerstyle: {
      text_color: "#FFFFFF",
      player_brand_color: "#000000",
      icon_color: "#FFFFFF",
      icon_button_color: "#000000",
      icon_button_opacity: "80",
      icon_button_hover_color: "#383838",
      center_icon_color: "#FFFFFF",
      center_icon_button_color: "#45474b",
      center_icon_button_opacity: "85",
      center_icon_button_hover_color: "#000000",
      progress_bar_BG_color: "#000000",
      progress_bar_loaded_color: "#a8a8a8",
      progress_bar_FG_color: "#939BA9",
      progress_bar_circle_color: "#FFFFFF",
      progress_bar_opacity: "100",
      settings_menu_BG_color: "#45474b",
      settings_menu_opacity: "100",
      settings_menu_BG_hover_color: "#000000",
      settings_menu_text_color: "#FFFFFF",
      tooltip_BG_color: "#45474B",
      tooltip_opacity: "100",
      tooltip_corner_radius: "4",
      tooltip_text_color: "#FFFFFF",
      volume_bar_BG_color: "#45474B",
      volume_bar_opacity: "100",
      volume_bar_FG_color: "#939BA9",
      player_corner_radius: "0",
      player_controls_margin: "20",
      bottom_bar_spacing: "16",
      icon_button_padding: "20",
      icon_button_corner_radius: "4",
      icon_button_size: "32",
      center_icon_button_padding: "38",
      center_icon_button_corner_radius: "8",
      center_icon_button_size: "70",
      progress_bar_size: "4",
      progress_bar_hover_scale: "2",
      volume_bar_size: "4",
      branding_opacity: "100",
    },
    playercontrol: {
      branding: true,
      thumbnail: false,
      video_frame: true,
      playpause: true,
      center_playpause: true,
      progress_bar: true,
      time_stamp: true,
      volume: true,
      full_screen_icon: true,
      video_name: false,
      settings_menu: true,
      back_button: false,
      gradient: true,
      osd_auto_hide: true,
      scrubber: true,
    },
    premium: {
      layoutConfig: {
        name: "halcyon",
      },
    },
  },
  moderna: {
    videotitle: "",
    videodescription: "",
    playerBrandingImageUrl:
      "https://sato-image-content.b-cdn.net/48d677f8-734a-496e-a2ec-ad6ef88411cc/50c87637-98f8-4378-b5b1-0f7a595a1b21/Sato.svg",
    playerThumbnailImageUrl: "",
    playersettings: {
      autoplay: false,
      muted: false,
      loop: false,
      use_as_BG_video: false,
    },
    playerstyle: {
      text_color: "#FFFFFF",
      player_brand_color: "#000000",
      icon_color: "#FFFFFF",
      icon_button_color: "transparent",
      icon_button_opacity: "100",
      icon_button_hover_color: "#77767b",
      center_icon_color: "#ffffff",
      center_icon_button_color: "transparent",
      center_icon_button_opacity: "100",
      center_icon_button_hover_color: "transparent",
      progress_bar_BG_color: "#45474B",
      progress_bar_loaded_color: "#0B0B0B",
      progress_bar_FG_color: "#939BA9",
      progress_bar_circle_color: "#FFFFFF",
      progress_bar_opacity: "100",
      settings_menu_BG_color: "#45474b",
      settings_menu_opacity: "100",
      settings_menu_BG_hover_color: "#000000",
      settings_menu_text_color: "#FFFFFF",
      tooltip_BG_color: "#45474B",
      tooltip_opacity: "100",
      tooltip_corner_radius: "4",
      tooltip_text_color: "#FFFFFF",
      volume_bar_BG_color: "#000000",
      volume_bar_opacity: "100",
      volume_bar_FG_color: "#ffffff",
      player_corner_radius: "0",
      player_controls_margin: "24",
      bottom_bar_spacing: "16",
      icon_button_padding: "16",
      icon_button_corner_radius: "12",
      icon_button_size: "24",
      center_icon_button_padding: "0",
      center_icon_button_corner_radius: "36",
      center_icon_button_size: "60",
      progress_bar_size: "4",
      progress_bar_hover_scale: "2",
      volume_bar_size: "4",
      branding_opacity: "100",
    },
    playercontrol: {
      branding: true,
      thumbnail: false,
      video_frame: true,
      playpause: true,
      center_playpause: true,
      progress_bar: true,
      time_stamp: true,
      volume: true,
      full_screen_icon: true,
      video_name: false,
      settings_menu: true,
      back_button: false,
      gradient: true,
      osd_auto_hide: true,
      scrubber: true,
    },
    premium: {
      layoutConfig: {
        name: "moderna",
        controls_bg: "#00000078",
        controls_padding: "12",
        controls_corner_radius: "35",
      },
      // playerCTA: {
      //   cta: false,
      //   url: "",
      //   buttonText: "",
      //   placement: "top-right",
      //   timing: "pre",
      //   direction: "vertical",
      //   heading: "",
      //   description: "",
      //   imageEnable: false,
      //   image: "",
      // },
      // rapidEngage: false,
      // caption: false,
    },
  },
  sphinx: {
    videotitle: "",
    videodescription: "",
    playerBrandingImageUrl:
      "https://sato-image-content.b-cdn.net/48d677f8-734a-496e-a2ec-ad6ef88411cc/50c87637-98f8-4378-b5b1-0f7a595a1b21/Sato.svg",
    playerThumbnailImageUrl: "",
    playersettings: {
      autoplay: false,
      muted: false,
      loop: false,
      use_as_BG_video: false,
    },
    playerstyle: {
      text_color: "#ffffff",
      player_brand_color: "#000000",
      icon_color: "#ffffff",
      icon_button_color: "transparent",
      icon_button_opacity: "100",
      icon_button_hover_color: "#333333",
      center_icon_color: "#ffffff",
      center_icon_button_color: "#000000",
      center_icon_button_opacity: "60",
      center_icon_button_hover_color: "#333333",
      progress_bar_BG_color: "#ababab",
      progress_bar_loaded_color: "#0B0B0B",
      progress_bar_FG_color: "#000000",
      progress_bar_circle_color: "#FFFFFF",
      progress_bar_opacity: "100",
      settings_menu_BG_color: "#45474b",
      settings_menu_opacity: "100",
      settings_menu_BG_hover_color: "#000000",
      settings_menu_text_color: "#FFFFFF",
      tooltip_BG_color: "#545454",
      tooltip_opacity: "100",
      tooltip_corner_radius: "4",
      tooltip_text_color: "#FFFFFF",
      volume_bar_BG_color: "#939BA9",
      volume_bar_opacity: "100",
      volume_bar_FG_color: "#c2c2c2",
      player_corner_radius: "0",
      player_controls_margin: "0",
      bottom_bar_spacing: "32",
      icon_button_padding: "16",
      icon_button_corner_radius: "4",
      icon_button_size: "24",
      center_icon_button_padding: "40",
      center_icon_button_corner_radius: "20",
      center_icon_button_size: "60",
      progress_bar_size: "4",
      progress_bar_hover_scale: "2",
      volume_bar_size: "3",
      branding_opacity: "100",
    },
    playercontrol: {
      branding: true,
      thumbnail: false,
      video_frame: true,
      playpause: true,
      center_playpause: true,
      progress_bar: true,
      time_stamp: true,
      volume: true,
      full_screen_icon: true,
      video_name: false,
      settings_menu: true,
      back_button: false,
      gradient: true,
      osd_auto_hide: true,
      scrubber: true,
    },
    premium: {
      layoutConfig: {
        name: "sphinx",
        controls_bg: "#00000095",
        controls_padding: "10",
        controls_corner_radius: "0",
      },
      // playerCTA: {
      //   cta: false,
      //   url: "",
      //   buttonText: "",
      //   placement: "top-right",
      //   timing: "pre",
      //   direction: "vertical",
      //   heading: "",
      //   description: "",
      //   imageEnable: false,
      //   image: "",
      // },
      // rapidEngage: false,
      // caption: false,
    },
  },
  prosper: {
    videotitle: "",
    videodescription: "",
    playerBrandingImageUrl:
      "https://sato-image-content.b-cdn.net/48d677f8-734a-496e-a2ec-ad6ef88411cc/50c87637-98f8-4378-b5b1-0f7a595a1b21/Sato.svg",
    playerThumbnailImageUrl: "",
    playersettings: {
      autoplay: false,
      muted: false,
      loop: false,
      use_as_BG_video: false,
    },
    playerstyle: {
      text_color: "#FFFFFF",
      player_brand_color: "#000000",
      icon_color: "#FFFFFF",
      icon_button_color: "transparent",
      icon_button_opacity: "100",
      icon_button_hover_color: "#3b3b3b",
      center_icon_color: "#ffffff",
      center_icon_button_color: "#00000090",
      center_icon_button_opacity: "70",
      center_icon_button_hover_color: "#3b3b3b",
      progress_bar_BG_color: "#000000",
      progress_bar_loaded_color: "#5c5c5c",
      progress_bar_FG_color: "#e8e8e8",
      progress_bar_circle_color: "#FFFFFF",
      progress_bar_opacity: "100",
      settings_menu_BG_color: "#45474b",
      settings_menu_opacity: "100",
      settings_menu_BG_hover_color: "#000000",
      settings_menu_text_color: "#FFFFFF",
      tooltip_BG_color: "#45474B",
      tooltip_opacity: "100",
      tooltip_corner_radius: "4",
      tooltip_text_color: "#FFFFFF",
      volume_bar_BG_color: "#939BA9",
      volume_bar_opacity: "100",
      volume_bar_FG_color: "#FFFFFF",
      player_corner_radius: "8",
      player_controls_margin: "16",
      bottom_bar_spacing: "0",
      icon_button_padding: "24",
      icon_button_corner_radius: "50",
      icon_button_size: "30",
      center_icon_button_padding: "40",
      center_icon_button_corner_radius: "50",
      center_icon_button_size: "60",
      progress_bar_size: "4",
      progress_bar_hover_scale: "2",
      volume_bar_size: "4",
      branding_opacity: "100",
    },
    playercontrol: {
      branding: true,
      thumbnail: false,
      video_frame: true,
      playpause: true,
      center_playpause: true,
      progress_bar: true,
      time_stamp: true,
      volume: true,
      full_screen_icon: true,
      video_name: false,
      settings_menu: true,
      back_button: false,
      gradient: true,
      osd_auto_hide: true,
      scrubber: true,
    },
    premium: {
      layoutConfig: {
        name: "prosper",
        controls_bg: "#2f242470",
        controls_padding: "6",
        controls_corner_radius: "30",
      },
      // playerCTA: {
      //   cta: false,
      //   url: "",
      //   buttonText: "",
      //   placement: "top-right",
      //   timing: "pre",
      //   direction: "vertical",
      //   heading: "",
      //   description: "",
      //   imageEnable: false,
      //   image: "",
      // },
      // rapidEngage: false,
      // caption: false,
    },
  },
};
