export const makeConfig = (
  json: any,
  source: any,
  mediaType: any,
  transcriptUrl: any,
) => {
  // console.log("makeConfig json →", json);
  // console.log("makeConfig source →", source);
  // console.log("makeConfig mediaType →", mediaType);

  return {
    src:
      source ||
      "https://splay-staging.b-cdn.net/8ec955f4-4c9b-48bd-9cfc-07d7e7580b1f/31453844-1763-4ce9-be2c-656a1e493395/90_Second_Timer.mp4",
    mediaType: mediaType || "mp4",
    brandImage: json?.playerBrandingImageUrl,
    videoThumbnail: json?.playerThumbnailImageUrl,
    enableSoftKeys: false,
    height: undefined,
    width: undefined,
    layout: json?.premium?.layoutConfig?.name || "halcyon",
    layoutConfig: {
      colors: {
        osdBg: json?.premium?.layoutConfig?.controls_bg,
        centerIconBg: json?.premium?.layoutConfig?.controls_bg,
      },
      spacing: {
        centerIconRadius: `${json?.premium?.layoutConfig?.controls_corner_radius}px`,
        centerIconPadding: `${json?.premium?.layoutConfig?.controls_padding}px`,
        osdPadding: `${json?.premium?.layoutConfig?.controls_padding}px`,
        osdRadius: `${json?.premium?.layoutConfig?.controls_corner_radius}px`,
      },
    },
    title: json?.videotitle,
    autoplay: json?.playersettings?.autoplay,
    muted: json?.playersettings?.muted,
    loop: json?.playersettings?.loop,
    showBrandImage: json?.playercontrol?.branding,
    showThumbnail: json?.playercontrol?.thumbnail,
    showVideoFrames: json?.playercontrol?.video_frame,
    showCenterPlayPause: json?.playercontrol?.center_playpause,
    showPlayPause: json?.playercontrol?.playpause,
    showProgressBar: json?.playercontrol?.progress_bar,
    showTimestamp: json?.playercontrol?.time_stamp,
    showScrubber: json?.playercontrol?.scrubber,
    showCaptions: json?.premium?.caption,
    captionSettings: {
      captionVtt: transcriptUrl,
    },
    showRapidEngageProgressBar: json?.premium?.rapidEngage,
    showVolumeBar: json?.playercontrol?.volume,
    showVideoTitle: json?.playercontrol?.video_name,
    showSettings: json?.playercontrol?.settings_menu,
    settingsPopupConfig: undefined,
    showFullscreen: json?.playercontrol?.full_screen_icon,
    showBackButton: json?.playercontrol?.back_button,
    showOSDGradient: json?.playercontrol?.gradient,
    // autoHideOSD: json?.playercontrol?.osd_auto_hide,
    autoHideOSD: false,
    showCta: json?.premium?.playerCTA?.cta,
    ctaConfig: {
      buttonText: json?.premium?.playerCTA?.buttonText,
      link: json?.premium?.playerCTA?.url,
      heading: json?.premium?.playerCTA?.heading,
      description: json?.premium?.playerCTA?.description,
      showImage: json?.premium?.playerCTA?.imageEnable,
      image: json?.premium?.playerCTA?.image,
      direction: json?.premium?.playerCTA?.direction,
      timing: json?.premium?.playerCTA?.timing,
      placement: json?.premium?.playerCTA?.placement,
    },
    theme: {
      colors: {
        primary: "#00b428",
        secondary: "#e8dd26",
        textColor: json?.playerstyle?.text_color,
        centerIconColor: json?.playerstyle?.center_icon_color,
        centerIconButtonColor: json?.playerstyle?.center_icon_button_color,
        centerIconButtonHoverColor:
          json?.playerstyle?.center_icon_button_hover_color,
        iconColor: json?.playerstyle?.icon_color,
        iconButtonColor: json?.playerstyle?.icon_button_color,
        iconButtonHoverColor: json?.playerstyle?.icon_button_hover_color,
        brandColor: json?.playerstyle?.player_brand_color,
        progressBGColor: json?.playerstyle?.progress_bar_BG_color,
        progressLoadedColor: json?.playerstyle?.progress_bar_loaded_color,
        progressForegroundColor: json?.playerstyle?.progress_bar_FG_color,
        progressCircleColor: json?.playerstyle?.progress_bar_circle_color,
        volumeBarBGColor: json?.playerstyle?.volume_bar_BG_color,
        volumeBarForegroundColor: json?.playerstyle?.volume_bar_FG_color,
        settingsBGColor: json?.playerstyle?.settings_menu_BG_color,
        settingsTextColor: json?.playerstyle?.settings_menu_text_color,
        settingsHoverColor: json?.playerstyle?.settings_menu_BG_hover_color,
        tooltipTextColor: json?.playerstyle?.tooltip_text_color,
        tooltipBGColor: json?.playerstyle?.tooltip_BG_color,
        textOpacity: `${json?.playerstyle?.text_opacity}%`,
        centerIconButtonOpacity: `${json?.playerstyle?.center_icon_button_opacity}%`,
        iconButtonOpacity: `${json?.playerstyle?.icon_button_opacity}%`,
        brandOpacity: `${json?.playerstyle?.branding_opacity}%`,
        progressOpacity: `${json?.playerstyle?.progress_bar_opacity}%`,
        volumeOpacity: `${json?.playerstyle?.volume_bar_opacity}%`,
        settingsOpacity: `${json?.playerstyle?.settings_menu_opacity}%`,
        tooltipOpacity: `${json?.playerstyle?.tooltip_opacity}%`,
      },
      spacing: {
        padding: "20px",
        margin: "4px",
        bottomBarSpacing: `${json?.playerstyle?.bottom_bar_spacing}px`,
        playerControlMargin: `${json?.playerstyle?.player_controls_margin}px`,
        playerCornerRadius: `${json?.playerstyle?.player_corner_radius}px`,
        centerIconButtonCornerRadius: `${json?.playerstyle?.center_icon_button_corner_radius}px`,
        centerIconButtonPadding: `${json?.playerstyle?.center_icon_button_padding}px`,
        centerIconButtonSize: `${json?.playerstyle?.center_icon_button_size}px`,
        iconButtonCornerRadius: `${json?.playerstyle?.icon_button_corner_radius}px`,
        iconButtonPadding: `${json?.playerstyle?.icon_button_padding}px`,
        iconButtonSize: `${json?.playerstyle?.icon_button_size}px`,
        progressBarHeight: `${json?.playerstyle?.progress_bar_size}px`,
        progressBarHoverScale: json?.playerstyle?.progress_bar_hover_scale,
        volumeBarHeight: `${json?.playerstyle?.volume_bar_size}px`,
        tooltipCornerRadius: `${json?.playerstyle?.tooltip_corner_radius}px`,
      },
    },
  };
};
